//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatalyaIvanova321_UhetPet.DataBaseUhet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets
    {
        public int PetID { get; set; }
        public string Names { get; set; }
        public string Opisanie { get; set; }
        public string ImagePath { get; set; }
    }
}
